{% set name = "raydar" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b5d297abcaed3d699d536ff1f8b14632d3413cf5447da99c8c17e0ecb1b55f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.3.1
  run:
    - python >={{ python_min }}
    - coolname
    - jinja2
    - pandas
    - polars
    - pyarrow
    - pydantic >=2
    - ray-serve >=2.8
    - spaday >=0.7,<0.8
    - spaday-perspective >=0.5,<0.6
    - spaday-webawesome >=0.2,<0.3
    - starlette
    - transports >=0.8,<0.9
    - uvicorn
    - websockets

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - raydar
  commands:
    - pip check

about:
  home: http://github.com/point72/raydar
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A perspective powered, user editable ray dashboard via ray serve
  description: A perspective powered, user editable ray dashboard via ray serve
  dev_url: https://github.com/point72/raydar

extra:
  recipe-maintainers:
    - gauglertodd
    - ptomecek
    - timkpaine
