{% set name = "raydar" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb554743e7791afc5029ca1041208f6ee0d902909585eceadd95f907fa151d49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.8
    - coolname
    - fastapi
    - packaging
    - perspective
    - polars
    - pydantic <2
    - ray-serve >=2.8

test:
  imports:
    - raydar
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/point72/raydar
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A perspective powered, user editable ray dashboard via ray serve
  description: A perspective powered, user editable ray dashboard via ray serve
  dev_url: https://github.com/point72/raydar

extra:
  recipe-maintainers:
    - gauglertodd
    - ptomecek
    - timkpaine
